### PR TITLE
added assignments

### LINKED ISSUE #4: Assignments (All andrew ng assignments weekwise folder )
All assignments of Deep learning
3 folders:- ( C1, C2, C4)
Folder name:- C1_name

### PR DESCRIPTION
**Pull request by labeeb-7z**
Closes #4

### CODE REVIEW

**Comment by Neel-Shah-29** [comment]
@labeeb-7z please add the assignments in the same folder where Lakshaya added just follow the naming convention. Course_Week_Name.ipynb

**Comment by labeeb-7z** [comment]
@Neel-Shah-29 done

**Review by Neel-Shah-29 — APPROVED** [review]

**Comment by Neel-Shah-29** [comment]
LGTM!
@shahpratham kindly review so that we can merge this PR!

**Review by shahpratham — CHANGES_REQUESTED** [review]
Looks good! @labeeb-7z 
Just link the PR to the corresponding issue as described [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), which will close the issue when the PR is merged.

**Comment by labeeb-7z** [comment]
@shahpratham done

**Pull request merged**
